const userController=require('../app/controllers/user.controller')
const {auth}=require('../app/middleWare')
const router=require('express').Router() 
router.post("/register",userController.register)
router.post("/logIn",userController.logIn)
router.get("/me",auth,userController.profile)
router.get("/",auth,userController.allusers)
router.post('/logout',auth,userController.logOut)
router.post('/logoutall',auth,userController.logOutAll)
router.get('/getsingle/:id',auth,userController.getSingle)
router.put('/changeStatus/:id/:status',auth,userController.changeStatus)
router.put('/editme',auth,userController.editUser)
router.patch('/edituser/:id',auth,userController.editUser)
router.delete('/deleteme',auth,userController.deleteUser)
router.delete('/deleteuser/:id',auth,userController.deleteUser)
router.put('/addaddress',auth,userController.addAddress)
router.delete('/deleteaddress/:id',auth,userController.deleteAddress)
router.get('/showalladdresses',auth,userController.showAllAddresses)
router.get('/showsingleaddress/:id',auth,userController.showSingleAddress)
router.put('/uploadimage',auth,userController.uploadMyImage)
module.exports=router