require('../DB/mongoose connection/dbconnection')
const express=require('express')
const hbs=require("hbs")
const path=require('path')
const app=express()
const taskRoutes=require('./routes/task.routes')
app.use(express.urlencoded({extended:true}))
app.use(express.static(path.join(__dirname,"../view/statics")))
app.set('view engine','hbs')
app.set("views",path.join(__dirname,"../view/views"))
hbs.registerPartials(path.join(__dirname,"../view/layouts"))
hbs.registerHelper('isId',value=>{return (value=='id')})
hbs.registerHelper('isContent',value=>{return (value=='content')})
hbs.registerHelper('isStatus',value=>{return (value=='status')})
app.use(taskRoutes)
module.exports=app